# Use Python 3.12 as base
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install pip dependencies
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt



# Copy the code
COPY app/ .

ENV PYTHONUNBUFFERED=1

EXPOSE 8501

# Command (used only in final container run)
#CMD ["python", "main.py"]
CMD ["streamlit", "run", "chat_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
