version: '3.8'
services:
  chatbot_ui:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: streamlit run chat_ui.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped

  fastapi_server:
    build: 
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
